[build-system]
requires = [
    "cmake>=3.26",
    "ninja",
    "packaging",
    "setuptools>=61",
    "setuptools-scm>=8.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "flash-float-jit-kernel"
authors = [{name = "yiakwy, and other flash-float authors"}]
license = { file = "LICENSE" }
description = "A low latency yet high-throughput and memory-efficient kernel library for low bit floats of LLM inference"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: Apache Software License",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Information Analysis",
]
requires-python = ">=3.9,<3.13"
dynamic = [ "version", "dependencies", "optional-dependencies"]

[project.urls]
"Homepage" = "https://github.com/yiakwy-xpu-ml-framework-team/flashFloat"
"Bug Tracker" = "https://github.com/yiakwy-xpu-ml-framework-team/flashFloat/issues"
Slack="http://slack.sglang.ai/"

[tool.setuptools_scm]
packages = ["jit_kernel"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["benchmarks", "docs", "examples", "tests*"]
namespaces = false

[tool.yapfignore]
ignore_patterns = [
    "build/**",
]

[tool.ruff]
# Allow lines to be as long as 80.
line-length = 80
exclude = [
    # External file, leaving license intact
    "examples/other/fp8/quantizer/quantize.py"
]

[tool.ruff.lint.per-file-ignores]
"vendors/**" = ["ALL"]
"python/jit_kernel/__version__.py" = ["ALL"]

[tool.wheel]
exclude = [
  "dist*",
  "tests*",
]

[tool.isort]
profile = "black"
use_parentheses = true
skip_gitignore = true

[tool.pytest.ini_options]
markers = [
    "skip_global_cleanup",
    "core_model: enable this model test in each PR instead of only nightly",
    "cpu_model: enable this model test in CPU tests",
    "quant_model: run this model test under Quantized category",
    "split: run this test as part of a split",
    "distributed: run this test only in distributed GPU tests",
    "skip_v1: do not run this test with v1",
    "optional: optional tests that are automatically skipped, include --optional to run them",
]

[tool.pymarkdown]
plugins.md004.style = "sublist" # ul-style
plugins.md013.enabled = false # line-length
plugins.md041.enabled = false # first-line-h1
plugins.md033.enabled = false # inline-html
plugins.md024.allow_different_nesting = true # no-duplicate-headers

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"jit_kernel" = ["csrc/**/*.cu", "csrc/**/*.h", "csrc/**/*.cpp", "csrc/**/*.cuh"]
